### ISSUE TITLE
chapter 10, issue concerning the auxiliary covariate for the estimation of the NDE 

### ISSUE THREAD

**Issue by grzebyk** [tlverse/tlverse-handbook#25] opened 2022-02-15 17:06 UTC
Many thanks for all your work.

I would like to point out an issue concerning the re-parametrization used  in the auxiliary covariate C_Y(Q_Z, g)(O) in Chapter 10. 

There is a discrepency between the re-parametrization in Chapter 10
		 p(A=0|Z,W)/p(A=1|Z,W)   g(0|W)/g(1|W)
and that  in the cited references,
  		p(A=0|Z,W)/p(A=1|Z,W) g(1|W)/g(0|W) (in Zheng and van der Laan 2012 for example)

I hope this will be useful

**Comment by nhejazi** [comment] 2022-04-26 23:59
Thank you for your careful attention to detail and for pointing out this error. The text has been corrected, and the issue is resolved in f7625002.

**Closed by nhejazi** 2022-04-26 23:59 UTC
Labels: bug
